### ISSUE TITLE
 How to convert bat to bash shell?

### ISSUE THREAD

**Issue by NhoLuong-IT** [daniel-sc/bash-shell-to-bat-converter#2]
Hi Daniel,

Please advice to me best solution with idea:  How to convert bat to bash shell?

Thank you very much?

**Comment by daniel-sc** [comment]
Hi @NhoLuong-IT ,

for this I don't really have a solution, as I never encountered the need for it. You are welcome to create a fork of this repository and implement the reverse!

Best, Daniel

**Comment by NhoLuong-IT** [comment]
Thanks Daniel

**Comment by deltabravozulu** [comment]
You could use something like batsh.org. If you learn the syntax, you can compile both .bat and .sh at the same time.
