### ISSUE TITLE
i need &&

### ISSUE THREAD

**Issue by dataf3l** [daniel-sc/bash-shell-to-bat-converter#33]
can I get && please?

**Comment by dataf3l** [comment]
@daniel-sc still cannot do it on the site, maybe site needs an update?

**Comment by daniel-sc** [comment]
Can you try again?

**Comment by dataf3l** [comment]
when I enter:

#!/bin/bash
echo 1 && echo 2

it produces:

@echo off

echo 1 && echo 2

which works as expected.

Thank you for teaching me, you are contributing to society.
This is why I love open-source.
Please never  stop being awesome.
