### ISSUE TITLE
Add LICENSE?

### ISSUE THREAD

**Issue by david-a-wheeler** [daniel-sc/bash-shell-to-bat-converter#4]
Hi, I was looking at using & extending this, but I don't see any LICENSE. Please add one!

I would recommend the MIT license, you can see that here: https://opensource.org/licenses/MIT#LicenseText

There are other good open source software licenses, including Apache 2.0, LGPL, and GPL. But please pick one.

I'll create a pull request to do this, but only you can decide if the license is what you want.

**Comment by david-a-wheeler** [comment]
I created a pull request that, if accepted, resolves this issue:

https://github.com/daniel-sc/bash-shell-to-bat-converter/pull/5

It's up to you what license you use, but I'd really like this use a common open source software license.

Thank you!

**Comment by daniel-sc** [comment]
Hi @david-a-wheeler 
The pr is merged - thanks!
Really like the idea of extending this first simple shot. I promise to merge PRs in a timely manner or give you corresponding access rights 😊
